name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".github/**"
      - "CHANGELOG.md"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - libc: musl
            platform: linux/386
            id: musl-i386
          - libc: musl
            platform: linux/amd64
            id: musl-amd64
    steps:
      - run: |
          matrix=$((
            echo '${{ toJSON(matrix) }}'
          ) | jq -c .)
          echo "$matrix" > matrix
          echo "::set-output name=matrix::$matrix"
        id: matrix
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.build_target == matrix.target || github.event.inputs.build_target == '*' || github.event.inputs.build_target == '')
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ hashFiles('matrix') || 'none' }}
          path: matrix
          if-no-files-found: warn

  check-matrix:
    runs-on: ubuntu-latest
    needs: [matrix]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          matrix="$(cat */matrix | jq -c --slurp .)"
          echo "::set-output name=matrix::$matrix"
        id: matrix

  manifest:
    needs: [check-matrix]
    runs-on: ubuntu-latest
    env:
      matrix: ${{ needs.check-matrix.outputs.matrix }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Manifest
        run: |
          gnu_containers=$($matrix | jq -r '[.[]|select(.libc=="gnu")|.id="typenoob/\(.id)"|.id]|join(" ")')
          musl_containers=$($matrix | jq -r '[.[]|select(.libc=="musl")|.id="typenoob/\(.id)"|.id]|join(" ")')
          docker manifest create typenoob/0.1-gnu $gnu_containers
          docker manifest create typenoob/0.1-musl $musl_containers
