name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".github/**"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - libc: musl
            platform: linux/386
          - libc: musl
            platform: linux/amd64
          - libc: musl
            platform: linux/arm/v6
          - libc: musl
            platform: linux/arm/v7
          - libc: musl
            platform: linux/arm64/v8
          - libc: musl
            platform: linux/ppc64le
          - libc: musl
            platform: linux/s390x
          - libc: gnu
            platform: linux/386
          - libc: gnu
            platform: linux/amd64
          - libc: gnu
            platform: linux/arm/v7
          - libc: gnu
            platform: linux/arm64/v8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          platforms: ${{ matrix.platform }}
          push: true
          tags: typenoob/nxbt:0.1-${{ matrix.libc }}
          file: docker/${{ matrix.libc }}/Dockerfile
      - name: Create the container
        run: docker create --platform ${{ matrix.platform }} --name extract nxbt:0.1-${{ matrix.libc }}
      - name: Copy the elf file
        run: sudo docker cp extract:/nxbt/build/cli/cli /artifacts/nxbt-${{ matrix.platform }}-${{ matrix.libc }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /artifacts
