name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".github/**"
      - "CHANGELOG.md"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - libc: musl
            platform: linux/386
            id: musl-i386
          - libc: musl
            platform: linux/amd64
            id: musl-amd64
          - libc: musl
            platform: linux/arm/v6
            id: musl-armv6
          - libc: musl
            platform: linux/arm/v7
            id: musl-armv7
          - libc: musl
            platform: linux/arm64/v8
            id: musl-aarch64
          - libc: musl
            platform: linux/ppc64le
            id: musl-ppc64le
          - libc: musl
            platform: linux/s390x
            id: musl-s390x
          - libc: gnu
            platform: linux/386
            id: gnu-i386
          - libc: gnu
            platform: linux/amd64
            id: gnu-amd64
          - libc: gnu
            platform: linux/arm/v7
            id: gnu-armv7
          - libc: gnu
            platform: linux/arm64/v8
            id: gnu-aarch64
    steps:
      - run: |
          matrix=$((
            echo '${{ toJSON(matrix) }}'
          ) | jq -c .)
          echo "$matrix" > matrix
          echo "::set-output name=matrix::$matrix"
        id: matrix
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.build_target == matrix.target || github.event.inputs.build_target == '*' || github.event.inputs.build_target == '')
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ hashFiles('matrix') || 'none' }}
          path: matrix
          if-no-files-found: warn

  check-matrix:
    runs-on: ubuntu-latest
    needs: [matrix]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          matrix="$(cat */matrix | jq -c --slurp .)"
          echo "::set-output name=matrix::$matrix"
        id: matrix

  manifest:
    needs: [check-matrix]
    runs-on: ubuntu-latest
    env:
      matrix: ${{ needs.check-matrix.outputs.matrix }}
      name: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Manifest
        run: |
          echo "gnu_containers=$(echo $matrix | jq -r '[.[]|select(.libc=="gnu")|.id="typenoob/\(.id)"|.id]|join(" ")') >> $GITHUB_ENV
          echo "musl_containers=$(echo $matrix | jq -r '[.[]|select(.libc=="musl")|.id="typenoob/\(.id)"|.id]|join(" ")') >> $GITHUB_ENV
          docker manifest create $name/0.1-gnu $gnu_containers
          docker manifest create $name/0.1-musl $musl_containers
