name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        default: dry-run
        type: string

jobs:
  matrix:
    runs-on: ubuntu-latest
    env:
      name: ghcr.io/${{ github.repository_owner }}
    strategy:
      matrix:
        include:
          - libc: musl
            platform: linux/amd64
            id: musl-amd64
          - libc: musl
            platform: linux/arm/v7
            id: musl-armv7
          - libc: musl
            platform: linux/arm64/v8
            id: musl-aarch64
          - libc: musl
            platform: linux/386
            id: musl-i386
          - libc: gnu
            platform: linux/amd64
            id: gnu-amd64
          - libc: gnu
            platform: linux/arm/v7
            id: gnu-armv7
          - libc: gnu
            platform: linux/arm64/v8
            id: gnu-aarch64
          - libc: gnu
            platform: linux/386
            id: gnu-i386
          - libc: msys2
            platform: linux/amd64
            id: mingw64
          - libc: msys2
            platform: linux/amd64
            id: ucrt64

    steps:
      - run: |
          matrix=$((
            echo '${{ toJSON(matrix) }}'
          ) | jq -c .)
          echo "$matrix" > matrix
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        id: matrix
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ hashFiles('matrix') || 'none' }}
          path: matrix
          if-no-files-found: warn

      - name: Checkout
        uses: actions/checkout@v4
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Uppercase Environment Variable
        id: prep
        run: |
          # Convert matrix.id to uppercase using bash string manipulation
          ID_RAW="${{ matrix.id }}"
          echo "msystem_upper=${ID_RAW^^}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.name }}/nxbt:${{ inputs.tag }}-${{ matrix.id }}
          file: docker/${{ matrix.libc }}/Dockerfile
          build-args: |
            MSYSTEM=${{ steps.prep.outputs.msystem_upper }}
  
      - name: Create the container
        run: docker create --platform ${{ matrix.platform }} --name extract $name/nxbt:${{ inputs.tag }}-${{ matrix.id }}
      
      - name: Copy the executable
        run: |
          if [ "${{ matrix.libc }}" = "msys2" ]; then
            sudo docker cp extract:/root/.wine/drive_c/msys64/usr/bin/nxbt.exe /nxbt-${{ matrix.id }}.exe
          else
            sudo docker cp extract:/nxbt/release/nxbt /nxbt-${{ matrix.id }}
          fi

      - name: Set artifact file path
        id: set-path
        run: |
          if [ "${{ matrix.libc }}" = "msys2" ]; then
            echo "FILE=/nxbt-${{ matrix.id }}.exe" >> $GITHUB_OUTPUT
          else
            echo "FILE=/nxbt-${{ matrix.id }}" >> $GITHUB_OUTPUT
          fi

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.id }}
          path: |
            ${{ steps.set-path.outputs.FILE }}

      - name: Release
        if: ${{ inputs.tag != 'dry-run' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          files: |
            ${{ steps.set-path.outputs.FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-matrix:
    runs-on: ubuntu-latest
    needs: [matrix]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/download-artifact@v4
      - run: |
          matrix="$(cat */matrix | jq -c --slurp .)"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        id: matrix

  manifest:
    needs: [check-matrix]
    runs-on: ubuntu-latest
    env:
      matrix: ${{ needs.check-matrix.outputs.matrix }}
      name: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Manifest
        run: |
          gnu_images=$(echo $matrix | jq -r --arg var $name '[.[]|select(.libc=="gnu")|.id="\($var)/nxbt:${{ inputs.tag }}-\(.id)"|.id]|join(" ")')
          if [ -n "$gnu_images" ]; then
            docker buildx imagetools create \
              -t $name/nxbt:${{ inputs.tag }}-gnu \
              -t $name/nxbt:gnu \
              -t $name/nxbt:${{ inputs.tag }} \
              -t $name/nxbt:latest \
              $gnu_images
          fi
          musl_images=$(echo $matrix | jq -r --arg var $name '[.[]|select(.libc=="musl")|.id="\($var)/nxbt:${{ inputs.tag }}-\(.id)"|.id]|join(" ")')
          if [ -n "$musl_images" ]; then
            docker buildx imagetools create \
              -t $name/nxbt:${{ inputs.tag }}-musl \
              -t $name/nxbt:musl \
              $musl_images
          fi
          mingw64_images=$(echo $matrix | jq -r --arg var $name '[.[]|select(.id=="mingw64")|.id="\($var)/nxbt:${{ inputs.tag }}-\(.id)"|.id]|join(" ")')
          if [ -n "$mingw64_images" ]; then
            docker buildx imagetools create \
              -t $name/nxbt:${{ inputs.tag }}-mingw64 \
              -t $name/nxbt:mingw64 \
              $mingw64_images
          fi
          ucrt64_images=$(echo $matrix | jq -r --arg var $name '[.[]|select(.id=="ucrt64")|.id="\($var)/nxbt:${{ inputs.tag }}-\(.id)"|.id]|join(" ")')
          if [ -n "$ucrt64_images" ]; then
            docker buildx imagetools create \
              -t $name/nxbt:${{ inputs.tag }}-ucrt64 \
              -t $name/nxbt:ucrt64 \
              $ucrt64_images
          fi