name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".github/**"
      - "CHANGELOG.md"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - libc: musl
            platform: linux/386
            id: musl-i386
    steps:
      - name: output
        id: output
        run: |
          echo "${{ toJson(matrix) }}"
    outputs:
      a: ${{ steps.output.outputs.a }}
      b: ${{ steps.output.outputs.b }}

  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Manifest
        run: |
          echo ${{ needs.build.strategy.matrix.id }}
          docker manifest create ${{ github.repository_owner }}
