name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".github/**"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libc: ["gnu", "musl"]
        arch: ["amd64", "arm64v8", "arm32v6", "arm32v7", "i386", "s390x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          platforms: busybox/${{ matrix.arch }}
          push: true
          tags: typenoob/nxbt:0.1-${{ matrix.libc }}
          file: docker/${{ matrix.libc }}/Dockerfile
      - name: Run the Docker image
        run: docker run --platform busybox/{{ matrix.arch }}-dit --name temp-${{ matrix.arch }}-${{ matrix.libc }} nxbt:0.1-${{ matrix.libc }} sh
      - name: Copy the elf file
        run: sudo docker cp temp-${{ matrix.arch }}-${{ matrix.libc }}:/nxbt/build/cli/cli /artifacts/nxbt-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            /artifacts
