name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - ".github/**"
      - "CHANGELOG.md"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - libc: musl
            platform: linux/386
            id: musl-i386
    steps:
      - name: output
        id: output
        run: |
          echo "output=${{ matrix.id }}" >> $GITHUB_OUTPUT
    outputs:
      ${{ matrix.id }}: ${{ steps.outputs.output }}

  manifest:
    needs: build
    runs-on: ubuntu-latest
    env:
      test: ${{ fromJson(needs.build.outputs) }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Manifest
        run: |
          echo $test
