name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build the Docker image
        run: docker build -t nxbt:0.1-musl -f docker/musl/Dockerfile ./docker

      - name: run the Docker image
        run: docker run -dit --name temp nxbt:0.1-musl sh

      - name: Copy the elf file
        run: docker cp temp:/bin/nxbt /nxbt
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nxbt
          path: |
            /nxbt
